# Generated by Django 4.2.4 on 2023-08-27 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='shop/', verbose_name='Attachment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'Item Attachment',
                'verbose_name_plural': 'Item Attachments',
            },
        ),
    ]
