# Generated by Django 4.2.4 on 2023-08-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_itemattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
